import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import { Link, Route, Switch, useLocation, useParams, Router as WouterRouter } from 'wouter';
import { ArrowRight, Check, ChevronDown, Clipboard, Download, FileJson, FileOutput, LoaderCircle, RotateCcw, Trash2, WandSparkles } from 'lucide-react';
import QRCode from 'qrcode';
import { PDFDocument } from 'pdf-lib';
import { categories, getTool, searchTools, tools, type Tool } from '@/data/tools';
import { AdSlot, FileUploader, Footer, Header, PrivacyNote, ToolCard, ToolFrame } from '@/components/toolnova-ui';
import NotFound from '@/pages/not-found';
import VideoConverter from '@/tools/video-converter';

const queryClient = new QueryClient();
const button = 'inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-px disabled:cursor-not-allowed disabled:opacity-50';
const outline = 'inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-background px-4 py-2.5 text-sm font-semibold transition-colors hover:bg-muted disabled:cursor-not-allowed disabled:opacity-50';
const input = 'w-full rounded-xl border border-input bg-background px-3.5 py-3 text-sm shadow-sm outline-none transition-colors placeholder:text-muted-foreground/70 focus:border-primary focus:ring-2 focus:ring-primary/15';
const textarea = `${input} min-h-44 resize-y font-mono leading-6`;
function downloadBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function downloadDataUrl(dataUrl: string, filename: string) { const a = document.createElement('a'); a.href = dataUrl; a.download = filename; a.click(); }
function prettyBytes(bytes: number) { return bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 / 1024).toFixed(2)} MB`; }
function copy(text: string) { if (text) navigator.clipboard?.writeText(text); }
function useObjectUrl(file?: File) { const [url, setUrl] = useState(''); useEffect(() => { if (!file) {setUrl(''); return;} const next = URL.createObjectURL(file); setUrl(next); return () => URL.revokeObjectURL(next); }, [file]); return url; }
function SectionTitle({ eyebrow, title, children }: { eyebrow?: string; title: string; children?: ReactNode }) { return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div>{eyebrow && <p className="mb-2 font-mono text-[11px] uppercase tracking-[.2em] text-accent">{eyebrow}</p>}<h2 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h2></div>{children}</div>; }
function Status({ children, error = false }: { children: ReactNode; error?: boolean }) { return <p className={`mt-3 rounded-xl px-3 py-2 text-sm ${error ? 'bg-destructive/10 text-destructive' : 'bg-secondary text-primary'}`} role={error ? 'alert' : 'status'} data-testid={error ? 'status-error' : 'status-success'}>{children}</p>; }

function Home() {
  const [, navigate] = useLocation(); const [query, setQuery] = useState('');
  const popular = tools.slice(0, 10);
  return <Page><main>
    <section className="mesh-bg border-b border-border/70"><div className="mx-auto grid max-w-7xl gap-10 px-4 pb-20 pt-16 sm:px-6 sm:pt-24 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pb-28">
      <div className="enter"><p className="mb-5 flex items-center gap-2 font-mono text-xs uppercase tracking-[.2em] text-primary"><span className="size-2 rounded-full bg-accent"/> The useful internet, organized</p><h1 className="max-w-3xl text-5xl font-bold leading-[.98] tracking-[-.055em] sm:text-7xl">Small task.<br/><span className="text-primary">Done properly.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">Free online tools for images, PDFs, text, developers and everyday calculations. No account, no upload queue, no detour.</p>
        <div className="relative mt-8 max-w-xl"><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => {if(e.key === 'Enter') navigate(`/tools${query ? `?q=${encodeURIComponent(query)}` : ''}`)}} className={`${input} h-14 pl-12 pr-28 text-base`} placeholder="Search for a tool..." aria-label="Search for a tool" data-testid="input-home-search"/><span className="absolute left-4 top-4 text-muted-foreground"><WandSparkles size={20}/></span><button className="absolute right-2 top-2 h-10 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground" onClick={() => navigate(`/tools${query ? `?q=${encodeURIComponent(query)}` : ''}`)} data-testid="button-home-search">Search</button></div>
        <div className="mt-5 flex flex-wrap gap-2 text-xs text-muted-foreground"><span>Try:</span>{['compress','PDF','JSON'].map((term) => <button key={term} onClick={() => {setQuery(term); navigate(`/tools?q=${term}`)}} className="rounded-full border border-border bg-card px-3 py-1 hover:border-primary hover:text-primary" data-testid={`button-suggestion-${term}`}>{term}</button>)}</div>
      </div>
      <div className="relative mx-auto w-full max-w-md lg:justify-self-end"><div className="absolute -inset-4 rounded-[2rem] bg-accent/10 blur-2xl"/><div className="relative overflow-hidden rounded-[2rem] border border-border bg-card p-5 shadow-xl"><div className="mb-4 flex items-center justify-between border-b border-border pb-4"><span className="font-mono text-xs text-muted-foreground">TOOLNOVA / QUICK ACCESS</span><span className="text-xs text-primary">{tools.length} live tools</span></div><div className="space-y-2">{['Image Compressor','PDF Merger','JSON Formatter','Password Generator'].map((name, i) => {const t = tools.find((x) => x.name === name)!; const Icon=t.icon; return <Link href={`/tools/${t.slug}`} key={name} className="flex items-center gap-3 rounded-xl p-3 transition-colors hover:bg-muted" data-testid={`link-hero-tool-${i}`}><span className="grid size-9 place-items-center rounded-lg bg-secondary text-primary"><Icon size={17}/></span><span className="text-sm font-medium">{name}</span><ArrowRight size={15} className="ml-auto text-muted-foreground"/></Link>})}</div><div className="mt-5 rounded-xl bg-primary p-4 text-primary-foreground"><p className="font-mono text-[10px] uppercase tracking-[.16em] opacity-70">Local by default</p><p className="mt-1 text-sm font-medium">Your files stay in the browser whenever possible.</p></div></div></div>
    </div></section>
    <div className="mx-auto max-w-7xl px-4 sm:px-6"><AdSlot/><section className="py-10"><SectionTitle eyebrow="Start here" title="Popular tools"><Link href="/tools" className="flex items-center gap-1 text-sm font-semibold text-primary" data-testid="link-popular-all">View all <ArrowRight size={15}/></Link></SectionTitle><div className="tool-grid grid gap-4">{popular.map((tool) => <ToolCard key={tool.id} tool={tool}/>)}</div></section>
    <section className="py-14"><SectionTitle eyebrow="The shelf" title="Browse by category"/><div className="grid gap-4 md:grid-cols-2">{categories.map((category, index) => {const list=tools.filter(t=>t.category===category).slice(0,3); return <div key={category} className={`rounded-2xl border border-border p-5 ${index%2 ? 'bg-secondary/45' : 'bg-card'}`}><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-bold">{category}</h3><span className="font-mono text-xs text-muted-foreground">{tools.filter(t=>t.category===category).length} tools</span></div><div className="space-y-1">{list.map((tool)=><Link href={`/tools/${tool.slug}`} key={tool.id} className="flex items-center justify-between rounded-lg px-3 py-2.5 text-sm hover:bg-background" data-testid={`link-category-${tool.slug}`}><span>{tool.name}</span><ArrowRight size={15} className="text-muted-foreground"/></Link>)}</div><Link href={`/tools?category=${category}`} className="mt-3 inline-flex text-xs font-semibold text-primary" data-testid={`link-category-all-${category}`}>Explore {category} <ArrowRight size={13} className="ml-1"/></Link></div>})}</div></section>
    <section className="grid gap-10 border-y border-border py-16 md:grid-cols-[.8fr_1.2fr]"><div><p className="mb-3 font-mono text-[11px] uppercase tracking-[.2em] text-accent">Why ToolNova?</p><h2 className="max-w-sm text-3xl font-bold tracking-tight sm:text-4xl">A toolbench, not a maze.</h2></div><div className="grid gap-7 sm:grid-cols-2">{[['01','Free to use','Useful means accessible. Every tool is ready without a paywall.'],['02','No registration','Open a tool and get on with it. We do not need your email.'],['03','Private by design','File processing happens in your browser whenever technically possible.'],['04','Fast on mobile','Focused interfaces, small payloads, and no clutter slowing you down.']].map(([n,t,d])=><div key={n}><span className="font-mono text-xs text-accent">{n}</span><h3 className="mt-2 font-semibold">{t}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{d}</p></div>)}</div></section>
    <section className="py-16"><SectionTitle eyebrow="Questions, answered" title="A better kind of utility shelf"/><div className="grid gap-3 md:grid-cols-2">{[['Do I need an account?','No. ToolNova is designed to work immediately, without registration or a cloud workspace.'],['Are my files uploaded?','For browser-capable operations, files stay on your device. We do not store user files.'],['What can I use ToolNova for?','Quick image conversions, PDF assembly, writing cleanup and developer utilities.'],['Does it work on phones?','Yes. Every tool is designed mobile-first, with touch-friendly controls and downloads.']].map(([q,a])=><details key={q} className="group rounded-xl border border-border bg-card p-4"><summary className="flex cursor-pointer list-none items-center justify-between font-medium">{q}<ChevronDown size={17} className="transition-transform group-open:rotate-180"/></summary><p className="pt-3 text-sm leading-6 text-muted-foreground">{a}</p></details>)}</div></section>
    </div></main></Page>;
}

function Page({ children }: { children: ReactNode }) { return <div className="noise min-h-[100dvh]"><Header/>{children}<Footer/></div>; }

function ToolsPage() {
  const params = new URLSearchParams(window.location.search); const [query, setQuery] = useState(params.get('q') ?? ''); const [category, setCategory] = useState(params.get('category') ?? 'All'); const filterCategories = [...categories, 'Calculators'];
  const found = useMemo(() => searchTools(query).filter(t => category === 'All' || t.category === category), [query, category]);
  return <Page><main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16"><div className="max-w-2xl"><p className="mb-3 font-mono text-[11px] uppercase tracking-[.2em] text-accent">The shelf / {tools.length} tools</p><h1 className="text-4xl font-bold tracking-tight sm:text-6xl">Find the right tool.</h1><p className="mt-4 text-muted-foreground">Search by name, file type, task, or category. Everything here is ready to run.</p></div><div className="mt-10 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><input value={query} onChange={(e)=>setQuery(e.target.value)} className={`${input} pl-11`} placeholder="Search tools, e.g. compress or JSON" aria-label="Search tools" data-testid="input-tools-search"/><span className="absolute left-3.5 top-3.5 text-muted-foreground">⌕</span></div><div className="flex flex-wrap gap-2" role="tablist" aria-label="Tool categories"><button className={`${category==='All'?button:outline} px-4`} onClick={()=>setCategory('All')} data-testid="button-category-all">All</button>{filterCategories.map(c=><button key={c} className={`${category===c?button:outline} px-4`} onClick={()=>setCategory(c)} data-testid={`button-category-${c}`}>{c}</button>)}</div></div><div className="mt-10 flex items-center justify-between"><p className="font-mono text-xs text-muted-foreground">{found.length.toString().padStart(2,'0')} results</p>{query && <button className="text-xs text-primary" onClick={()=>setQuery('')} data-testid="button-clear-search">Clear search</button>}</div>{found.length ? <div className="tool-grid mt-4 grid gap-4">{found.map(tool=><ToolCard key={tool.id} tool={tool}/>)}</div> : <div className="mt-4 rounded-2xl border border-dashed border-border p-14 text-center"><p className="font-semibold">{category==='Calculators'?'Calculators are being prepared for a future shelf.':'Nothing in the drawer yet.'}</p><p className="mt-2 text-sm text-muted-foreground">Try another phrase or browse every category.</p><button className={`${outline} mt-5`} onClick={()=>{setQuery('');setCategory('All')}} data-testid="button-reset-tools">Reset filters</button></div>}</main></Page>;
}

function ToolPage() {
  const { slug } = useParams<{slug:string}>(); const tool = getTool(slug);
  useEffect(() => { if (!tool) return; document.title = `${tool.seoTitle}`; const setMeta = (selector: string, attrs: Record<string,string>) => { const node = document.querySelector(selector) ?? document.head.appendChild(document.createElement('meta')); Object.entries(attrs).forEach(([key,value])=>node.setAttribute(key,value)); return node; }; setMeta('meta[name="description"]',{name:'description',content:tool.seoDescription}); setMeta('meta[property="og:title"]',{property:'og:title',content:tool.seoTitle}); setMeta('meta[property="og:description"]',{property:'og:description',content:tool.seoDescription}); const canonical = document.querySelector('link[rel="canonical"]') ?? document.head.appendChild(document.createElement('link')); canonical.setAttribute('rel','canonical'); canonical.setAttribute('href',`${window.location.origin}/tools/${tool.slug}`); const ld = document.createElement('script'); ld.type='application/ld+json'; ld.textContent=JSON.stringify({'@context':'https://schema.org','@type':'WebApplication',name:tool.name,description:tool.seoDescription,applicationCategory:'UtilitiesApplication',operatingSystem:'Any'}); document.head.appendChild(ld); return ()=>{ld.remove()}; }, [tool]);
  if (!tool) return <NotFound/>; const related = tools.filter(t=>t.category===tool.category && t.id!==tool.id).slice(0,4);
  return <Page><main className="mx-auto max-w-7xl px-4 py-9 sm:px-6 sm:py-14"><div className="mb-8"><div className="mb-5 flex items-center gap-2 text-xs text-muted-foreground"><Link href="/tools" className="hover:text-primary" data-testid="link-breadcrumb-tools">All tools</Link><span>/</span><span>{tool.category}</span><span>/</span><span className="text-foreground">{tool.name}</span></div><p className="mb-3 font-mono text-[11px] uppercase tracking-[.2em] text-accent">{tool.category} tool</p><h1 className="text-4xl font-bold tracking-tight sm:text-5xl">{tool.name}</h1><p className="mt-3 max-w-2xl text-base text-muted-foreground">{tool.description}</p></div><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_280px]"><div><ToolInterface tool={tool}/><PrivacyNote/></div><aside className="hidden lg:block"><AdSlot label="ToolNova / space"/><div className="rounded-2xl border border-border bg-card p-5"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Quick note</p><p className="mt-3 text-sm leading-6 text-muted-foreground">No account is needed. Your work stays in this browser unless a tool explicitly says otherwise.</p></div></aside></div><AdSlot/><section className="mt-12 grid gap-10 border-t border-border pt-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="mb-2 font-mono text-[11px] uppercase tracking-[.2em] text-accent">How it works</p><h2 className="text-2xl font-bold">Focused by design.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Choose your input, make the adjustment, and download the result. ToolNova keeps the controls close to the task so you can finish quickly.</p></div><div className="space-y-3">{['Add your input using the uploader or editor.','Adjust the options that matter for your task.','Run the tool, review the result, then download it.'].map((s,i)=><div key={s} className="flex items-start gap-3 rounded-xl bg-card p-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-secondary font-mono text-xs text-primary">{i+1}</span><p className="pt-1 text-sm">{s}</p></div>)}</div></section><section className="mt-12"><h2 className="mb-5 text-2xl font-bold">Related tools</h2><div className="tool-grid grid gap-4">{related.map(t=><ToolCard key={t.id} tool={t}/>)}</div></section></main></Page>;
}

function ToolInterface({ tool }: { tool: Tool }) {
  if (tool.category === 'Images') return <ImageTool tool={tool}/>;
  if (tool.category === 'PDF') return <PdfTool tool={tool}/>;
  if (tool.slug === 'video-format-converter') return <VideoConverter/>;
  if (tool.slug === 'word-counter') return <WordCounter/>;
  if (tool.slug === 'case-converter') return <CaseConverter/>;
  if (tool.slug === 'remove-duplicate-lines') return <DuplicateLines/>;
  if (tool.slug === 'text-to-slug') return <SlugTool/>;
  if (tool.slug === 'password-generator') return <PasswordTool/>;
  if (tool.slug === 'json-formatter') return <JsonTool/>;
  return <Base64Tool/>;
}

function ImageTool({ tool }: { tool: Tool }) {
  if (tool.slug === 'qr-code-generator') return <QrTool/>;
  const [file, setFile] = useState<File>(); const [quality, setQuality] = useState(tool.slug==='image-compressor'? .75 : .86); const [width, setWidth] = useState(800); const [height, setHeight] = useState(600); const [keep, setKeep] = useState(true); const [result, setResult] = useState<{url:string;size:number;type:string}>(); const [message,setMessage]=useState('');
  const url = useObjectUrl(file); const isBase64=tool.slug==='image-to-base64'; const isCrop=tool.slug==='image-cropper';
  useEffect(()=>{if(!file)return; const img=new Image(); img.onload=()=>{setWidth(img.naturalWidth);setHeight(img.naturalHeight)}; img.src=url},[file,url]);
  const process = async () => { if(!file || !url) {setMessage('Choose an image first.');return;} setMessage(''); if(isBase64){const reader=new FileReader();reader.onload=()=>setResult({url:String(reader.result),size:String(reader.result).length,type:'text/plain'});reader.readAsDataURL(file);return;} const img=new Image(); img.onload=()=>{const canvas=document.createElement('canvas'); const w=isCrop?Math.min(width,img.naturalWidth):width; const h=isCrop?Math.min(height,img.naturalHeight):(tool.slug==='image-resizer'&&keep?Math.round(width*img.naturalHeight/img.naturalWidth):height); canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx)return; if(tool.slug==='png-to-jpg') {ctx.fillStyle='#f7f3e9';ctx.fillRect(0,0,w,h)} ctx.drawImage(img,0,0,w,h);const type=tool.slug==='jpg-to-png'?'image/png':tool.slug==='webp-converter'?'image/webp':tool.slug==='png-to-jpg'||tool.slug==='image-compressor'?'image/jpeg':file.type; const out=canvas.toDataURL(type,quality); fetch(out).then(r=>r.blob()).then(blob=>setResult({url:out,size:blob.size,type}))};img.src=url; };
  const ext=tool.slug==='jpg-to-png'?'png':tool.slug==='webp-converter'?'webp':tool.slug==='png-to-jpg'||tool.slug==='image-compressor'?'jpg':'png';
  return <ToolFrame title={tool.name}><FileUploader accept={tool.slug==='jpg-to-png'?'image/jpeg':'image/jpeg,image/png,image/webp'} onFiles={(fs)=>{setFile(fs[0]);setResult(undefined);setMessage('')}} files={file?[file]:[]} label={file ? 'Replace image' : 'Choose an image'}/>{file && <div className="mt-6 grid gap-6 md:grid-cols-2"><div className="overflow-hidden rounded-xl border border-border bg-muted p-2"><img src={url} alt="Selected preview" className="max-h-72 w-full object-contain" data-testid="img-preview"/></div><div className="space-y-4">{(tool.slug==='image-resizer'||isCrop) && <div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Width<input type="number" min="1" value={width} onChange={e=>setWidth(Number(e.target.value))} className={`${input} mt-1`} data-testid="input-image-width"/></label><label className="text-sm font-medium">Height<input type="number" min="1" value={height} onChange={e=>setHeight(Number(e.target.value))} className={`${input} mt-1`} data-testid="input-image-height"/></label></div>}{tool.slug==='image-resizer'&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={keep} onChange={e=>setKeep(e.target.checked)} data-testid="input-keep-ratio"/> Maintain aspect ratio</label>}{['image-compressor','png-to-jpg','webp-converter'].includes(tool.slug)&&<label className="block text-sm font-medium">Quality <span className="font-mono text-muted-foreground">{Math.round(quality*100)}%</span><input type="range" min=".1" max="1" step=".01" value={quality} onChange={e=>setQuality(Number(e.target.value))} className="mt-3 w-full accent-primary" data-testid="input-image-quality"/></label>}{isBase64&&<p className="rounded-xl bg-muted p-3 text-xs leading-5 text-muted-foreground">The generated data URL can be pasted into HTML, CSS or a JSON payload.</p>}<div className="flex flex-wrap gap-2"><button className={button} onClick={process} data-testid="button-process-image">{isBase64?'Generate Base64':tool.slug==='image-resizer'?'Resize image':'Convert image'} <ArrowRight size={16}/></button>{result&&<button className={outline} onClick={()=>isBase64?downloadBlob(new Blob([result.url],{type:'text/plain'}),'image-base64.txt'):downloadDataUrl(result.url,`toolnova-${tool.slug}.${ext}`)} data-testid="button-download-image"><Download size={16}/> Download</button>}</div>{result&&<Status><Check size={15} className="mr-1 inline"/> Ready · {prettyBytes(result.size)}{file&& !isBase64 && ` · ${Math.max(0,Math.round((1-result.size/file.size)*100))}% smaller`}</Status>}{message&&<Status error>{message}</Status>}</div></div>}</ToolFrame>;
}

function QrTool() {
  const [text, setText] = useState(''); const [data, setData] = useState(''); const [error, setError] = useState('');
  const generate = async () => { if (!text.trim()) { setError('Enter text or a URL first.'); return; } try { setError(''); setData(await QRCode.toDataURL(text.trim(), { width: 640, margin: 2, color: { dark: '#202638', light: '#f7f3e9' } })); } catch { setError('QR code generation failed. Try a shorter input.'); } };
  return <ToolFrame title="QR Code Generator"><label className="text-sm font-medium">Text or URL<textarea value={text} onChange={e=>setText(e.target.value)} className={`${textarea} mt-2 min-h-32`} placeholder="https://toolnova.tools" data-testid="textarea-qr-input"/></label><div className="mt-4 flex gap-2"><button className={button} onClick={generate} data-testid="button-generate-qr">Generate QR code</button><button className={outline} onClick={()=>{setText('');setData('');setError('')}} data-testid="button-clear-qr">Clear</button></div>{error&&<Status error>{error}</Status>}{data&&<div className="mt-7 flex flex-col items-center gap-4 rounded-2xl bg-muted p-5"><img src={data} alt="Generated QR code" className="size-64 rounded-lg" data-testid="img-qr-output"/><button className={button} onClick={()=>downloadDataUrl(data,'toolnova-qr-code.png')} data-testid="button-download-qr"><Download size={16}/> Download PNG</button></div>}</ToolFrame>;
}

function PdfTool({ tool }: { tool: Tool }) {
  const [files,setFiles]=useState<File[]>([]); const [pages,setPages]=useState('1'); const [result,setResult]=useState<Uint8Array>(); const [jpgs,setJpgs]=useState<string[]>([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const imageMode=tool.slug==='jpg-to-pdf';
  const createPdf=async()=>{setBusy(true);setMessage('');setResult(undefined);setJpgs([]);try{if(tool.slug==='jpg-to-pdf'){const pdf=await PDFDocument.create();for(const file of files){const bytes=await file.arrayBuffer();const image=file.type==='image/png'?await pdf.embedPng(bytes):await pdf.embedJpg(bytes);const page=pdf.addPage([image.width,image.height]);page.drawImage(image,{x:0,y:0,width:image.width,height:image.height})}setResult(await pdf.save())}else if(tool.slug==='pdf-to-jpg'){const pdfjs=await import('pdfjs-dist/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.mjs',import.meta.url).toString();const doc=await pdfjs.getDocument({data:new Uint8Array(await files[0].arrayBuffer())}).promise;const selected=pages.split(',').flatMap(part=>{const [a,b]=part.split('-').map(Number);return b?Array.from({length:b-a+1},(_,i)=>a+i):[a]}).filter(p=>p>0&&p<=doc.numPages);const images:string[]=[];for(const pageNum of selected){const page=await doc.getPage(pageNum);const viewport=page.getViewport({scale:1.5});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d')!,viewport}).promise;images.push(canvas.toDataURL('image/jpeg',.92))}setJpgs(images)}else{const pdfs=await Promise.all(files.map(async f=>PDFDocument.load(await f.arrayBuffer())));if(tool.slug==='pdf-merger'){const out=await PDFDocument.create();for(const doc of pdfs){const copied=await out.copyPages(doc,doc.getPageIndices());copied.forEach((p)=>out.addPage(p))}setResult(await out.save())}else{const src=pdfs[0];const out=await PDFDocument.create();const selected=pages.split(',').flatMap(part=>{const [a,b]=part.split('-').map(Number);return b?Array.from({length:b-a+1},(_,i)=>a+i-1):[a-1]}).filter(i=>i>=0&&i<src.getPageCount());const copied=await out.copyPages(src,selected);copied.forEach((p)=>out.addPage(p));setResult(await out.save())}}}catch{setMessage('That file could not be processed. Check the format and selected pages.')}finally{setBusy(false)}};
  return <ToolFrame title={tool.name}><FileUploader accept={imageMode?'image/jpeg,image/png,image/webp':'application/pdf'} multiple={tool.slug==='pdf-merger'||imageMode} onFiles={setFiles} files={files} label={imageMode?'Add images':'Add PDF files'}/>{files.length>0&&<div className="mt-6 space-y-4">{(tool.slug==='pdf-splitter'||tool.slug==='pdf-page-extractor'||tool.slug==='pdf-to-jpg')&&<label className="block text-sm font-medium">Pages or ranges <input value={pages} onChange={e=>setPages(e.target.value)} className={`${input} mt-2`} placeholder="1, 3-5" data-testid="input-pdf-pages"/><span className="mt-1 block text-xs font-normal text-muted-foreground">Example: 1, 3-5. Page numbers start at 1.</span></label>}<div className="flex flex-wrap gap-2"><button className={button} onClick={createPdf} disabled={busy} data-testid="button-process-pdf">{busy?<LoaderCircle className="animate-spin" size={16}/>:<FileOutput size={16}/>} {tool.slug==='jpg-to-pdf'?'Create PDF':tool.slug==='pdf-merger'?'Merge PDFs':tool.slug==='pdf-to-jpg'?'Convert pages':'Extract pages'}</button>{result&&<button className={outline} onClick={()=>downloadBlob(new Blob([result as unknown as BlobPart],{type:'application/pdf'}),`toolnova-${tool.slug}.pdf`)} data-testid="button-download-pdf"><Download size={16}/> Download PDF</button>}</div>{result&&<Status><Check size={15} className="mr-1 inline"/> PDF ready · {prettyBytes(result.byteLength)}</Status>}{jpgs.length>0&&<div className="grid gap-3 sm:grid-cols-2">{jpgs.map((src,i)=><div key={src} className="rounded-xl bg-muted p-3"><img src={src} alt={`Converted PDF page ${i+1}`} className="max-h-64 w-full object-contain"/><button className={`${outline} mt-3 w-full`} onClick={()=>downloadDataUrl(src,`toolnova-page-${i+1}.jpg`)} data-testid={`button-download-page-${i+1}`}><Download size={15}/> Download page {i+1}</button></div>)}</div>}{message&&<Status error>{message}</Status>}</div>}</ToolFrame>;
}

function WordCounter(){const [text,setText]=useState('');const words=text.trim()?text.trim().split(/\s+/).length:0;const chars=text.length;const sentences=text.trim()?text.split(/[.!?]+/).filter(s=>s.trim()).length:0;const paragraphs=text.trim()?text.split(/\n\s*\n/).filter(Boolean).length:0;return <ToolFrame><textarea value={text} onChange={e=>setText(e.target.value)} className={textarea} placeholder="Paste or write your text here..." aria-label="Text to count" data-testid="textarea-word-counter"/><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{[['Words',words],['Characters',chars],['No spaces',text.replace(/\s/g,'').length],['Sentences',sentences],['Paragraphs',paragraphs],['Read time',`${Math.max(0,Math.ceil(words/220))} min`]].map(([label,value])=><div key={label} className="rounded-xl bg-muted p-3"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold" data-testid={`text-counter-${label}`}>{value}</p></div>)}</div><div className="mt-4 flex justify-end"><button className={outline} onClick={()=>setText('')} data-testid="button-clear-counter"><Trash2 size={15}/> Clear</button></div></ToolFrame>}
function CaseConverter(){const [text,setText]=useState('');const convert=(mode:string)=>{const words=text.toLowerCase().split(/(\s+)/);if(mode==='upper')return text.toUpperCase();if(mode==='lower')return text.toLowerCase();if(mode==='title')return words.map(w=>w.trim()?w[0].toUpperCase()+w.slice(1):w).join('');if(mode==='sentence')return text.toLowerCase().replace(/(^\s*|[.!?]\s+)([a-z])/g,(_,a,b)=>a+b.toUpperCase());return words.map(w=>w.trim()?w[0].toUpperCase()+w.slice(1):w).join('')};const [out,setOut]=useState('');return <ToolFrame><textarea value={text} onChange={e=>{setText(e.target.value);setOut(e.target.value)}} className={textarea} placeholder="Type or paste text..." data-testid="textarea-case-input"/><div className="mt-4 flex flex-wrap gap-2">{[['upper','UPPERCASE'],['lower','lowercase'],['title','Title Case'],['sentence','Sentence case'],['each','Capitalize Each Word']].map(([mode,label])=><button key={mode} className={outline} onClick={()=>setOut(convert(mode))} data-testid={`button-case-${mode}`}>{label}</button>)}</div><textarea value={out} readOnly className={`${textarea} mt-5`} placeholder="Converted text appears here" data-testid="textarea-case-output"/><div className="mt-3 flex gap-2"><button className={button} onClick={()=>copy(out)} data-testid="button-copy-case"><Clipboard size={15}/> Copy</button><button className={outline} onClick={()=>{setText('');setOut('')}} data-testid="button-clear-case">Clear</button></div></ToolFrame>}
function DuplicateLines(){const [text,setText]=useState('');const [ignore,setIgnore]=useState(true);const [out,setOut]=useState('');const run=()=>{const seen=new Set<string>();const lines=text.split(/\r?\n/).filter(line=>!ignore||line.trim());setOut(lines.filter(line=>{const key=line.trim();if(seen.has(key))return false;seen.add(key);return true}).join('\n'))};return <ToolFrame><textarea value={text} onChange={e=>setText(e.target.value)} className={textarea} placeholder="Paste a list with one item per line..." data-testid="textarea-duplicates"/><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={ignore} onChange={e=>setIgnore(e.target.checked)} data-testid="input-ignore-empty"/> Ignore empty lines</label><div className="mt-4 flex gap-2"><button className={button} onClick={run} data-testid="button-remove-duplicates">Remove duplicates</button><button className={outline} onClick={()=>{setText('');setOut('')}} data-testid="button-clear-duplicates">Clear</button></div>{out&&<><textarea readOnly value={out} className={`${textarea} mt-5`} data-testid="textarea-duplicates-output"/><div className="mt-3 flex gap-2"><button className={button} onClick={()=>copy(out)} data-testid="button-copy-duplicates"><Clipboard size={15}/> Copy</button><button className={outline} onClick={()=>downloadBlob(new Blob([out],{type:'text/plain'}),'unique-lines.txt')} data-testid="button-download-duplicates"><Download size={15}/> Download</button></div></>}</ToolFrame>}
function SlugTool(){const [text,setText]=useState('');const slug=text.normalize('NFKD').replace(/[^\w\s-]/g,'').trim().toLowerCase().replace(/[\s_-]+/g,'-').replace(/^-+|-+$/g,'');return <ToolFrame><label className="text-sm font-medium">Phrase<input value={text} onChange={e=>setText(e.target.value)} className={`${input} mt-2`} placeholder="My Amazing Online Tool" data-testid="input-slug"/></label><div className="mt-5 rounded-xl bg-muted p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Slug output</p><p className="mt-2 break-all font-mono text-lg text-primary" data-testid="text-slug-output">{slug||'your-clean-slug'}</p></div><div className="mt-4 flex gap-2"><button className={button} disabled={!slug} onClick={()=>copy(slug)} data-testid="button-copy-slug"><Clipboard size={15}/> Copy</button><button className={outline} onClick={()=>setText('')} data-testid="button-clear-slug">Clear</button></div></ToolFrame>}
function PasswordTool(){const [length,setLength]=useState(18);const [options,setOptions]=useState({upper:true,lower:true,numbers:true,symbols:true});const [password,setPassword]=useState('');const generate=()=>{let chars='';if(options.upper)chars+='ABCDEFGHJKLMNPQRSTUVWXYZ';if(options.lower)chars+='abcdefghijkmnopqrstuvwxyz';if(options.numbers)chars+='23456789';if(options.symbols)chars+='!@#$%^&*_-+=';if(!chars){setPassword('');return}const values=new Uint32Array(length);crypto.getRandomValues(values);setPassword(Array.from(values,v=>chars[v%chars.length]).join(''))};const strength=password.length>=20&&options.symbols?'Strong':password.length>=12?'Good':'Fair';return <ToolFrame><div className="flex flex-col gap-6 sm:flex-row"><div className="flex-1"><label className="text-sm font-medium">Password length <span className="font-mono text-muted-foreground">{length}</span><input type="range" min="8" max="64" value={length} onChange={e=>setLength(Number(e.target.value))} className="mt-3 w-full accent-primary" data-testid="input-password-length"/></label><div className="mt-5 grid grid-cols-2 gap-3">{Object.entries(options).map(([key,value])=><label key={key} className="flex items-center gap-2 text-sm capitalize"><input type="checkbox" checked={value} onChange={e=>setOptions({...options,[key]:e.target.checked})} data-testid={`input-password-${key}`}/>{key}</label>)}</div></div><div className="flex-1 rounded-xl bg-muted p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Generated password</p><p className="mt-4 min-h-14 break-all font-mono text-xl font-bold" data-testid="text-password-output">{password||'Click generate'}</p>{password&&<p className="mt-2 text-xs text-primary">{strength} strength</p>}</div></div><div className="mt-6 flex gap-2"><button className={button} onClick={generate} data-testid="button-generate-password"><RotateCcw size={15}/> Generate</button><button className={outline} disabled={!password} onClick={()=>copy(password)} data-testid="button-copy-password"><Clipboard size={15}/> Copy</button></div></ToolFrame>}
function JsonTool(){const [text,setText]=useState('');const [out,setOut]=useState('');const [error,setError]=useState('');const run=(minify:boolean)=>{try{const parsed=JSON.parse(text);setOut(JSON.stringify(parsed,null,minify?0:2));setError('')}catch(e){setError(e instanceof Error?e.message:'Invalid JSON');setOut('')}};return <ToolFrame><textarea value={text} onChange={e=>{setText(e.target.value);setError('')}} className={`${textarea} min-h-64`} placeholder={'{"name":"ToolNova","ready":true}'} data-testid="textarea-json-input"/><div className="mt-4 flex flex-wrap gap-2"><button className={button} onClick={()=>run(false)} data-testid="button-format-json"><FileJson size={15}/> Format</button><button className={outline} onClick={()=>run(true)} data-testid="button-minify-json">Minify</button><button className={outline} onClick={()=>{try{JSON.parse(text);setError('Valid JSON');}catch(e){setError(e instanceof Error?e.message:'Invalid JSON')}}} data-testid="button-validate-json">Validate</button><button className={outline} onClick={()=>{setText('');setOut('');setError('')}} data-testid="button-clear-json">Clear</button></div>{error&&<Status error>{error==='Valid JSON'?<><Check size={15} className="mr-1 inline"/> Valid JSON</>:error}</Status>}{out&&<div className="mt-5"><textarea value={out} readOnly className={`${textarea} min-h-64`} data-testid="textarea-json-output"/><div className="mt-3 flex gap-2"><button className={button} onClick={()=>copy(out)} data-testid="button-copy-json"><Clipboard size={15}/> Copy</button><button className={outline} onClick={()=>downloadBlob(new Blob([out],{type:'application/json'}),'formatted.json')} data-testid="button-download-json"><Download size={15}/> Download</button></div></div>}</ToolFrame>}
function Base64Tool(){const [mode,setMode]=useState<'encode'|'decode'>('encode');const [inputValue,setInputValue]=useState('');const [out,setOut]=useState('');const [error,setError]=useState('');const run=()=>{try{setError('');setOut(mode==='encode'?btoa(unescape(encodeURIComponent(inputValue))):decodeURIComponent(escape(atob(inputValue))))}catch{setError(mode==='encode'?'Could not encode this input.':'That is not valid Base64 text.');setOut('')}};return <ToolFrame><div className="mb-5 flex rounded-xl bg-muted p-1"><button className={`flex-1 rounded-lg px-3 py-2 text-sm font-semibold ${mode==='encode'?'bg-card shadow-sm':''}`} onClick={()=>setMode('encode')} data-testid="button-base64-encode">Encode</button><button className={`flex-1 rounded-lg px-3 py-2 text-sm font-semibold ${mode==='decode'?'bg-card shadow-sm':''}`} onClick={()=>setMode('decode')} data-testid="button-base64-decode">Decode</button></div><textarea value={inputValue} onChange={e=>setInputValue(e.target.value)} className={textarea} placeholder={mode==='encode'?'Text to encode...':'Base64 to decode...'} data-testid="textarea-base64-input"/><div className="mt-4 flex gap-2"><button className={button} onClick={run} data-testid="button-process-base64">{mode==='encode'?'Encode':'Decode'}</button><button className={outline} onClick={()=>{setInputValue('');setOut('');setError('')}} data-testid="button-clear-base64">Clear</button></div>{error&&<Status error>{error}</Status>}{out&&<div className="mt-5"><textarea readOnly value={out} className={textarea} data-testid="textarea-base64-output"/><button className={`${button} mt-3`} onClick={()=>copy(out)} data-testid="button-copy-base64"><Clipboard size={15}/> Copy</button></div>}</ToolFrame>}

function InfoPage({ kind }: { kind: 'about'|'contact'|'privacy-policy'|'terms'|'cookie-policy' }) {const data={about:['About ToolNova','A small, independent utility shelf for getting practical things done online.'],contact:['Contact','Have a suggestion, spot a problem, or want to talk about a partnership? We would like to hear from you.'], 'privacy-policy':['Privacy policy','ToolNova is built around a simple rule: your files should not travel farther than the task requires.'],terms:['Terms of service','These terms describe the straightforward, fair use of ToolNova.'], 'cookie-policy':['Cookie policy','ToolNova keeps its use of cookies intentionally small.'] }[kind];return <Page><main className="mx-auto max-w-3xl px-4 py-14 sm:px-6 sm:py-20"><p className="mb-3 font-mono text-[11px] uppercase tracking-[.2em] text-accent">ToolNova / {kind.replace('-', ' ')}</p><h1 className="text-4xl font-bold tracking-tight sm:text-6xl">{data[0]}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{data[1]}</p><div className="prose prose-slate mt-12 max-w-none dark:prose-invert"><h2>Made for quick, useful work</h2><p>ToolNova provides browser-first utilities for images, documents, writing and development. There is no account system in this version and no requirement to upload files to a remote service.</p><h2>Our approach</h2><p>We keep interfaces direct, explain what is happening, and avoid collecting information that is not needed to run a tool. The product is still evolving, so this page is a clear starting point for the final policy and contact details.</p>{kind==='contact'&&<div className="not-prose mt-8 rounded-2xl border border-border bg-card p-6"><p className="text-sm text-muted-foreground">For now, send a note to <strong className="text-foreground">hello@toolnova.tools</strong>.</p></div>}<h2>Questions</h2><p>If you need clarification about a tool or how local processing works, contact the ToolNova team before sharing anything sensitive.</p></div></main></Page>}

function Router() { return <ErrorBoundary resetKey={window.location.pathname}><Switch><Route path="/" component={Home}/><Route path="/tools" component={ToolsPage}/><Route path="/tools/:slug" component={ToolPage}/><Route path="/about"><InfoPage kind="about"/></Route><Route path="/contact"><InfoPage kind="contact"/></Route><Route path="/privacy-policy"><InfoPage kind="privacy-policy"/></Route><Route path="/terms"><InfoPage kind="terms"/></Route><Route path="/cookie-policy"><InfoPage kind="cookie-policy"/></Route><Route component={NotFound}/></Switch></ErrorBoundary>; }
function App(){useEffect(()=>{if(localStorage.getItem('toolnova-theme')==='dark')document.documentElement.classList.add('dark')},[]);return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/,'')}><Router/></WouterRouter><Toaster/></TooltipProvider></QueryClientProvider>}
export default App;